In [56]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [57]:
dataset=pd.read_csv('Company_Data.csv')
dataset

Sales  CompPrice  Income  Advertising  Population  Price ShelveLoc  Age  \
0     9.50        138      73           11         276    120       Bad   42   
1    11.22        111      48           16         260     83      Good   65   
2    10.06        113      35           10         269     80    Medium   59   
3     7.40        117     100            4         466     97    Medium   55   
4     4.15        141      64            3         340    128       Bad   38   
..     ...        ...     ...          ...         ...    ...       ...  ...   
395  12.57        138     108           17         203    128      Good   33   
396   6.14        139      23            3          37    120    Medium   55   
397   7.41        162      26           12         368    159    Medium   40   
398   5.94        100      79            7         284     95       Bad   50   
399   9.71        134      37            0          27    120      Good   49   

     Education Urban   US  
0           17   Yes  Yes  
1           10   Yes  Yes  
2           12   Yes  Yes  
3           14   Yes  Yes  
4           13   Yes   No  
..         ...   ...  ...  
395         14   Yes  Yes  
396         11    No  Yes  
397         18   Yes  Yes  
398         12   Yes  Yes  
399         16   Yes  Yes  

[400 rows x 11 columns]

In [5]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Sales        400 non-null    float64
 1   CompPrice    400 non-null    int64  
 2   Income       400 non-null    int64  
 3   Advertising  400 non-null    int64  
 4   Population   400 non-null    int64  
 5   Price        400 non-null    int64  
 6   ShelveLoc    400 non-null    object 
 7   Age          400 non-null    int64  
 8   Education    400 non-null    int64  
 9   Urban        400 non-null    object 
 10  US           400 non-null    object 
dtypes: float64(1), int64(7), object(3)
memory usage: 34.5+ KB


In [6]:
dataset.isnull().sum()

Sales          0
CompPrice      0
Income         0
Advertising    0
Population     0
Price          0
ShelveLoc      0
Age            0
Education      0
Urban          0
US             0
dtype: int64

## Converting Sales to category

In [58]:
data=dataset
data.describe()

Sales   CompPrice      Income  Advertising  Population  \
count  400.000000  400.000000  400.000000   400.000000  400.000000   
mean     7.496325  124.975000   68.657500     6.635000  264.840000   
std      2.824115   15.334512   27.986037     6.650364  147.376436   
min      0.000000   77.000000   21.000000     0.000000   10.000000   
25%      5.390000  115.000000   42.750000     0.000000  139.000000   
50%      7.490000  125.000000   69.000000     5.000000  272.000000   
75%      9.320000  135.000000   91.000000    12.000000  398.500000   
max     16.270000  175.000000  120.000000    29.000000  509.000000   

            Price         Age   Education  
count  400.000000  400.000000  400.000000  
mean   115.795000   53.322500   13.900000  
std     23.676664   16.200297    2.620528  
min     24.000000   25.000000   10.000000  
25%    100.000000   39.750000   12.000000  
50%    117.000000   54.500000   14.000000  
75%    131.000000   66.000000   16.000000  
max    191.000000   80.000000   18.000000

In [59]:
data['Sales']=pd.cut(x=data['Sales'],bins=[0,6,12,17],labels=['Low','Medium','High'],right=False)
data

Sales  CompPrice  Income  Advertising  Population  Price ShelveLoc  Age  \
0    Medium        138      73           11         276    120       Bad   42   
1    Medium        111      48           16         260     83      Good   65   
2    Medium        113      35           10         269     80    Medium   59   
3    Medium        117     100            4         466     97    Medium   55   
4       Low        141      64            3         340    128       Bad   38   
..      ...        ...     ...          ...         ...    ...       ...  ...   
395    High        138     108           17         203    128      Good   33   
396  Medium        139      23            3          37    120    Medium   55   
397  Medium        162      26           12         368    159    Medium   40   
398     Low        100      79            7         284     95       Bad   50   
399  Medium        134      37            0          27    120      Good   49   

     Education Urban   US  
0           17   Yes  Yes  
1           10   Yes  Yes  
2           12   Yes  Yes  
3           14   Yes  Yes  
4           13   Yes   No  
..         ...   ...  ...  
395         14   Yes  Yes  
396         11    No  Yes  
397         18   Yes  Yes  
398         12   Yes  Yes  
399         16   Yes  Yes  

[400 rows x 11 columns]

## Splitting data to temp variables

In [60]:
x_temp=data.iloc[:,1:]
y_temp=data.iloc[:,0]

In [61]:
x_temp

CompPrice  Income  Advertising  Population  Price ShelveLoc  Age  \
0          138      73           11         276    120       Bad   42   
1          111      48           16         260     83      Good   65   
2          113      35           10         269     80    Medium   59   
3          117     100            4         466     97    Medium   55   
4          141      64            3         340    128       Bad   38   
..         ...     ...          ...         ...    ...       ...  ...   
395        138     108           17         203    128      Good   33   
396        139      23            3          37    120    Medium   55   
397        162      26           12         368    159    Medium   40   
398        100      79            7         284     95       Bad   50   
399        134      37            0          27    120      Good   49   

     Education Urban   US  
0           17   Yes  Yes  
1           10   Yes  Yes  
2           12   Yes  Yes  
3           14   Yes  Yes  
4           13   Yes   No  
..         ...   ...  ...  
395         14   Yes  Yes  
396         11    No  Yes  
397         18   Yes  Yes  
398         12   Yes  Yes  
399         16   Yes  Yes  

[400 rows x 10 columns]

In [62]:
x_temp=pd.get_dummies(x_temp)

In [18]:
x_temp

CompPrice  Income  Advertising  Population  Price  Age  Education  \
0          138      73           11         276    120   42         17   
1          111      48           16         260     83   65         10   
2          113      35           10         269     80   59         12   
3          117     100            4         466     97   55         14   
4          141      64            3         340    128   38         13   
..         ...     ...          ...         ...    ...  ...        ...   
395        138     108           17         203    128   33         14   
396        139      23            3          37    120   55         11   
397        162      26           12         368    159   40         18   
398        100      79            7         284     95   50         12   
399        134      37            0          27    120   49         16   

     ShelveLoc_Bad  ShelveLoc_Good  ShelveLoc_Medium  Urban_No  Urban_Yes  \
0                1               0                 0         0          1   
1                0               1                 0         0          1   
2                0               0                 1         0          1   
3                0               0                 1         0          1   
4                1               0                 0         0          1   
..             ...             ...               ...       ...        ...   
395              0               1                 0         0          1   
396              0               0                 1         1          0   
397              0               0                 1         0          1   
398              1               0                 0         0          1   
399              0               1                 0         0          1   

     US_No  US_Yes  
0        0       1  
1        0       1  
2        0       1  
3        0       1  
4        1       0  
..     ...     ...  
395      0       1  
396      0       1  
397      0       1  
398      0       1  
399      0       1  

[400 rows x 14 columns]

## Check the score for individual features

In [63]:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2

bestfeatures=SelectKBest(score_func=chi2,k=5)
fit=bestfeatures.fit(x_temp,y_temp)
# calculate the scores
dfscore=pd.DataFrame(fit.scores_)
# get column names into variable
dfcolumns=pd.DataFrame(x_temp.columns)
# concat 2 dataframe above
feat_col=pd.concat([dfcolumns,dfscore],axis=1)
feat_col.columns=['Specs','Score'] # Naming the DataFrame
print(feat_col.nlargest(5,'Score'))

            Specs       Score
4           Price  249.402227
2     Advertising  144.508146
1          Income   80.520134
5             Age   66.427476
8  ShelveLoc_Good   61.724317


In [64]:
x_temp.head()

CompPrice  Income  Advertising  Population  Price  Age  Education  \
0        138      73           11         276    120   42         17   
1        111      48           16         260     83   65         10   
2        113      35           10         269     80   59         12   
3        117     100            4         466     97   55         14   
4        141      64            3         340    128   38         13   

   ShelveLoc_Bad  ShelveLoc_Good  ShelveLoc_Medium  Urban_No  Urban_Yes  \
0              1               0                 0         0          1   
1              0               1                 0         0          1   
2              0               0                 1         0          1   
3              0               0                 1         0          1   
4              1               0                 0         0          1   

   US_No  US_Yes  
0      0       1  
1      0       1  
2      0       1  
3      0       1  
4      1       0

# Solve with Feature Scaling

   ## Bring every feature on the same scale except ShelveLoc as it is already between 0 and 1

In [79]:
tran_x=x_temp.loc[:,['Price','Advertising','Income','Age','ShelveLoc_Bad','ShelveLoc_Medium','ShelveLoc_Good']]
tran_x

Price  Advertising  Income  Age  ShelveLoc_Bad  ShelveLoc_Medium  \
0      120           11      73   42              1                 0   
1       83           16      48   65              0                 0   
2       80           10      35   59              0                 1   
3       97            4     100   55              0                 1   
4      128            3      64   38              1                 0   
..     ...          ...     ...  ...            ...               ...   
395    128           17     108   33              0                 0   
396    120            3      23   55              0                 1   
397    159           12      26   40              0                 1   
398     95            7      79   50              1                 0   
399    120            0      37   49              0                 0   

     ShelveLoc_Good  
0                 0  
1                 1  
2                 0  
3                 0  
4                 0  
..              ...  
395               1  
396               0  
397               0  
398               0  
399               1  

[400 rows x 7 columns]

In [66]:
y_temp

0      Medium
1      Medium
2      Medium
3      Medium
4         Low
        ...  
395      High
396    Medium
397    Medium
398       Low
399    Medium
Name: Sales, Length: 400, dtype: category
Categories (3, object): ['Low' < 'Medium' < 'High']

In [80]:
tran_x

Price  Advertising  Income  Age  ShelveLoc_Bad  ShelveLoc_Medium  \
0      120           11      73   42              1                 0   
1       83           16      48   65              0                 0   
2       80           10      35   59              0                 1   
3       97            4     100   55              0                 1   
4      128            3      64   38              1                 0   
..     ...          ...     ...  ...            ...               ...   
395    128           17     108   33              0                 0   
396    120            3      23   55              0                 1   
397    159           12      26   40              0                 1   
398     95            7      79   50              1                 0   
399    120            0      37   49              0                 0   

     ShelveLoc_Good  
0                 0  
1                 1  
2                 0  
3                 0  
4                 0  
..              ...  
395               1  
396               0  
397               0  
398               0  
399               1  

[400 rows x 7 columns]

In [68]:
y_temp

0      Medium
1      Medium
2      Medium
3      Medium
4         Low
        ...  
395      High
396    Medium
397    Medium
398       Low
399    Medium
Name: Sales, Length: 400, dtype: category
Categories (3, object): ['Low' < 'Medium' < 'High']

## Split Train and Test Data

In [81]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(tran_x, y_temp, test_size = 0.3, random_state = 1)

In [82]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
sc.fit_transform(X_train)
sc.fit_transform(X_test)

array([[-0.83779853,  0.13860795,  0.36582658, -0.21404631,  1.90141648,
        -1.16316   , -0.51298918],
       [-2.65352209, -0.89175204,  0.33192759, -0.65799422, -0.52592371,
         0.85972695, -0.51298918],
       [-0.20624251, -0.74455776, -0.07486027,  0.10305934,  1.90141648,
        -1.16316   , -0.51298918],
       [ 0.38584126, -0.3029749 , -0.820638  , -0.59457309, -0.52592371,
        -1.16316   ,  1.94935887],
       [-0.24571476,  1.02177366,  1.14550331, -1.16536325, -0.52592371,
        -1.16316   ,  1.94935887],
       [ 0.07006325,  1.02177366,  1.14550331,  1.1177974 , -0.52592371,
         0.85972695, -0.51298918],
       [ 0.85950827, -0.89175204, -0.24435521,  1.43490305, -0.52592371,
         0.85972695, -0.51298918],
       [-1.07463204, -0.89175204,  0.06073569, -0.91167873,  1.90141648,
        -1.16316   , -0.51298918],
       [-0.56149277,  1.31616223,  1.04380634,  0.29332272,  1.90141648,
        -1.16316   , -0.51298918],
       [-0.79832628,  0.7273

## Try with different estimators and max_depth

In [105]:
from sklearn.ensemble import RandomForestClassifier
# Default values
classifier = RandomForestClassifier(n_estimators = 100, criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

RandomForestClassifier(criterion='entropy', random_state=0)

In [106]:
y_pred = classifier.predict(X_test)

### Confusion Matrix

In [107]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[ 3  0  6]
 [ 0 21 16]
 [ 3 11 60]]


0.7

In [117]:
# estimator 100 max depth 5
classifier = RandomForestClassifier(n_estimators = 100, criterion = 'entropy', random_state = 0,max_depth=5)
classifier.fit(X_train, y_train)

RandomForestClassifier(criterion='entropy', max_depth=5, random_state=0)

In [118]:
y_pred = classifier.predict(X_test)

In [119]:
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[ 1  0  8]
 [ 0 19 18]
 [ 1  6 67]]


0.725

## Gini

In [120]:
classifier = RandomForestClassifier(n_estimators = 100, criterion = 'gini', random_state = 0)
classifier.fit(X_train, y_train)

RandomForestClassifier(random_state=0)

In [121]:
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[ 2  0  7]
 [ 0 20 17]
 [ 3 11 60]]


0.6833333333333333

In [123]:
classifier = RandomForestClassifier(n_estimators = 100, criterion = 'gini', random_state = 0,max_depth=5)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[ 1  0  8]
 [ 0 19 18]
 [ 0  8 66]]


0.7166666666666667